import { describe, expect, it } from 'vitest';
import { isValidToken } from '../shared/src/index.ts';

describe('isValidToken', () => {
  it('accepts URL-safe alphanumeric tokens', () => {
    expect(isValidToken('a1B2c3')).toBe(true);
    expect(isValidToken('guest-42')).toBe(true);
    expect(isValidToken('guest_42')).toBe(true);
    expect(isValidToken('x')).toBe(true);
  });

  it('rejects empty, oversized or unsafe tokens', () => {
    expect(isValidToken('')).toBe(false);
    expect(isValidToken('a b')).toBe(false);
    expect(isValidToken('a/b')).toBe(false);
    expect(isValidToken('ñandú')).toBe(false);
    expect(isValidToken('a'.repeat(65))).toBe(false);
    expect(isValidToken('a'.repeat(64))).toBe(true);
  });

  it('accepts base64url tokens generated by scripts/generate-tokens.mjs', () => {
    // base64url alphabet: A-Z a-z 0-9 - _
    expect(isValidToken('QWERTYuio-9_')).toBe(true);
  });
});
